export const orderStatusOject = {
    1:"Đang xử lý",
    2:"Bị huỷ",
    3:"Hoàn thành",
}

export const typeProduct = {
    1:"Dịch vụ",
    2:"Thẻ dịch vụ",
    3:"Sản phẩm",
}


export const defaultExprotOrder = {
    order_code: "Mã hóa đơn", 
    order_at: "Ngày tạo hóa đơn",
    customer_name: "Tên khách hàng",
    customer_mobile: "Số điện thoại",
    customer_code: "Mã KH",
    customer_new_old: "Khách mới/khách quay lại",
    group_cutomer: "Nhóm KH",
    source_from: "Nguồn đặt lịch",
    status: "Trạng thái",
    total_price_before: "Tổng tiền trước giảm giá",
    discount_by_total_bill: "Giảm giá",
    price_point: "Đổi điểm thành tiền",
    discount_by_rule: "Voucher",
    total_price: "Tổng tiền đơn hàng",
    total_sales: "Tổng doanh số",
    money_owed: "Còn nợ",
    pay_money : "Thu bằng Tiền mặt",
    pay_banking:"Thu bằng Chuyển khoản",
    pay_card: "Thu bằng Quẹt thẻ",
    pay_electronic: "Thu bằng Ví điện tử",
    cod: "Thu bằng Ship COD",
    deposit_total: "Thanh toán bằng thẻ cọc",
    update_name: "Nhân viên thu ngân",
    create_name:"Nhân viên Đặt lịch",
    // count_customer: "Số khách hàng đi nhóm",
    voucher_code: "Mã voucher sử dụng",
    points: "Điểm thưởng được nhận",
    note: "Gi chú"
}

export const defaultExprotOrderDetail = { 
    order_code: "Mã hóa đơn", 
    order_at: "Ngày tạo hóa đơn",
    customer_name: "Tên khách hàng",
    customer_mobile: "Số điện thoại",
    // customer_code: "Mã KH",
    product_name: "Dịch vụ & sản phẩm",
    package_code: "Mã dịch vụ & sản phẩm",
    type_product: "Loại d.vụ & sp",
    quantity: "Số lượng",
    // total_price_after_discount: "Doanh thu trước giảm giá",
    // discount_order_item: "Giảm giá từng mục",
    // total_price_before: "Giảm giá bởi tổng hoá đơn",
    // price_point: "Giảm giá bởi đổi điểm",
    // voucher_discount: "Giảm giá bởi voucher",
    total_price: "Doanh thu sau khi giảm giá",
    // amount_deducted_from_membership_card: "Số tiền trừ vào thẻ thành viên (bao gồm cả thẻ lần)",
    // discount_card_money: "Trừ vào thẻ tiền",
    pay_type: "Loại thanh toán",
    customer_new_old: "Khách mới/quay lại",
    source_from: "Nguồn đặt lịch",
    create_name: "NV Đặt lịch",
    status: "Trạng thái",
    employee_service_name1: "Nhân viên 1",
    // sommission_service1: "Hoa hồng dịch vụ 1",
    employee_service_name2: "Nhân viên 2",
    // sommission_service2: "Hoa hồng dịch vụ 2",
    // employee_service_name3: "Nhân viên 3",
    // sommission_service3:"Hoa hồng dịch vụ 3",
    // employee_service_name4: "Nhân viên 4",
    // sommission_service4: "Hoa hồng dịch vụ 4",
    // employee_service_name5: "Nhân viên 5",
    // sommission_service5: "Hoa hồng dịch vụ 5",
    employee_sell1: "Nhân viên bán hàng 1",
    sommission_sell1: "Hoa hồng bán hàng 1",
    employee_sell2: "Nhân viên bán hàng 2",
    sommission_sell2: "Hoa hồng bán hàng 2",
    employee_consultant_name1: "Nhân viên tư vấn 1",
    sommission_consultant1: "Hoa hồng tư vấn 1",
    employee_consultant_name2: "Nhân viên tư vấn 2",
    sommission_consultant2: "Hoa hồng tư vấn 2",
    // employee_consultant_name3: "Nhân viên tư vấn 3",
    // sommission_consultant3: "Hoa hồng tư vấn 3",
    // employee_consultant_name4: "Nhân viên tư vấn 4",
    // sommission_consultant4: "Hoa hồng tư vấn 4",
    // employee_consultant_name5: "Nhân viên tư vấn 5",
    // sommission_consultant5: "Hoa hồng tư vấn 5",
    // commission_presenter: "Hoa hồng giới thiệu",
    update_name: "Người tạo hóa đơn",
    price_ktv:" Tiền Dịch Vụ KTV",
    // node: "Ghi chú",
}